---
title: "TermProject"
author: "Julia"
date: "2023-09-26"
output: html_document
---

```{r packages}
library(readr)
library(tidyverse)
library(ggplot2)
library(stringr)
```

```{r data import}
data <- read_csv("https://raw.githubusercontent.com/hereisjulia/DataScience_MQM/main/TermProject/Loan_default.csv")
View(data)
```

```{r data overview}
str(data)
summary(data)
length(data)
count(data)
```
```{r}
ggplot(data=data)+
  geom_col(aes(x = Age, y = Default))
```

```{r}
ggplot(data=data)+
  geom_area(aes(x=Income, y=Default))
```

```{r}
testCorr$HasMortgage <- ifelse(testCorr$HasMortgage == "Yes", 1, 0)
testCorr$HasDependents <- ifelse(testCorr$HasDependents == "Yes", 1, 0)
testCorr$HasCoSigner <- ifelse(testCorr$HasDependents == "Yes", 1, 0)

testCorr
```



```{r}
library(corrplot)
testCorr <- data[,-1]
testCorr <- na.omit(testCorr)
Corr <- cor(testCorr)
CorrplotColor <- brewer.pal(n = 4, name = "BrBG")
corrplot(Corr, method = "square", col = rev(CorrplotColor), tl.col = "black")
```



















